version: "3"

services:
  reverse-proxy:
    image: nginx:mainline-alpine
    volumes:
      - ./client/build:/var/www/fcs/build
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api
      - socket

  api:
    build: ./api
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27018/fcs
    depends_on:
      - mongodb
    restart: always

  socket:
    build: ./socket
    environment:
      NODE_ENV: production

  mongodb:
    image: "mongo"
    ports:
      - 27018:27018
    volumes:
      - db-data:/data/db
    command: mongod --port 27018 --bind_ip_all

volumes:
  db-data:
